---
aliases: aliases
devs_group: false
backup_rsync_target: s134.okserver.org
check_mk_port: 6556
ckan_sysadmin_email: 'ckan-sysadmin@okfn.org'
docker_host: false
graphite_port: 2003
graphite_server: graphite.okfn.org
hostname_tld: okserver.org
iptables_config_file: '/etc/iptables/rules.v4'
locale_list:
  - en_GB.utf8
mail_domains: []
monitoring_server: nagios.okfn.org
#monitoring_server_ip is required by the check_mk agent role
monitoring_server_ip: 52.5.139.123
enabled_plugin_checks: mk_inodes
munin_port: 4949
nagios_additional_hosts:
  - blogfarm.okserver.org
openspending_sysadmin_email: 'openspending-sysadmin@okfn.org'
sysadmin_email: 'sysadmin-alert@okfn.org'
timezone: Etc/UTC
users_extra: []
users_purge:
  - vitor
sudo_default:
  - "%sudo"
  - "%sysadmin"
sudo_extras: []
sudo_extra_lines: []
postgres_port: 5432
solr_port: 8983
sshd_PasswordAuthentication: No
