---
hosted: aws
users_extra:
  - name: 'pudo'
    groups:
      - openspending_dev
    authorized_keys:
      - 'pudo'
  - name: 'stiivi'
    groups:
      - openspending_dev
    authorized_keys:
      - 'stiivi'
sudo_extras:
  - tryggvib
sudo_extra_lines:
  - '%openspending_dev ALL=(ALL) NOPASSWD: /usr/bin/supervisorctl *'
