- name: install xinetd
  apt: pkg=xinetd state=installed

- name: setup check-mk-agent based on distribution
  include: debian.yml
  when: ansible_distribution == 'Debian'

- name: setup check-mk-agent based on distribution
  include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: setup check_mk xinetd file
  template: src=check_mk.j2 dest=/etc/xinetd.d/check_mk owner=root group=root mode=644
  tags: check_mk-xinetd
  notify: reload xinetd

- name: add firewall rule for check_mk
  lineinfile: dest="{{ iptables_config_file }}"
              regexp='dport "{{ check_mk_port }}" -j monitoring$'
              line='-A INPUT -s "{{ monitoring_server }}" -p tcp -m tcp --dport "{{ check_mk_port }}" -j monitoring' insertbefore='^COMMIT' state=present
  notify: restart iptables-persistent

- name: setup_plugin_checks
  copy: src=usr/lib/check_mk_agent/plugins/{{ item }}
        dest=/usr/lib/check_mk_agent/plugins/{{ item }}
        mode=0755
  with_items: enabled_plugin_checks
  when: enabled_plugin_checks is defined
