#ansible-playbook main.yml --tags="base-roles" -vvv
---
- hosts: all
  sudo: true
  vars_files:
    - vars/users.yml
    - "{{ private_dir }}/p.yml"
  roles:
    - { role: set-facts, tags: ['sudo'] }
    - { role: ansible-prereq, tags: ['ansible-prereq'] }
    - check-mk-agent
    - { role: collectd, tags: ['collectd'] }
    - { role: cron, tags: ['cron'] }
    - { role: iptables-persistent, tags: ['iptables-persistent'] }
    - { role: motd, tags: ['motd'] }
    - { role: nagios-client, tags: ['nagios-client'] }
    - postfix
    - { role: knopki.timezone, tags: ['time'] }
    - { role: bennojoy.ntp, tags: ['time'] }
    - { role: sysstat, tags: ['sysstat'] }
    - { role: update-notifier, tags: ['update-notifier'] }
    - { role: users, tags: ['users'] }
    - { role: sudo , tags: ['sudo'] }
    - { role: git, tags: ['git'] }
    - { role: db-backup, tags: ['db-backup'] }
    - { role: apt-mirror-config, tags: ['apt-mirror-config'] }
    - { role: unattended-upgrades, tags: ['unattended-upgrades'] }

- hosts: openspending-solr
  sudo: true
  roles:
    - { role: python, tags: ['python'] }
    - { role: supervisor, tags: ['supervisor'] }

- hosts: openspending-web
  sudo: true
  vars_files:
    - "{{ private_dir }}/p.yml"
  roles:
    - { role: varnish, tags: ['varnish'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: statsd, tags: ['statsd'] }

- hosts: s134.okserver.org
  sudo: true
  vars_files:
    - "{{ private_dir }}/p.yml"
  roles:
    - { role: okfn-org-manager, tags: ['heroku-backup'] }

- hosts: s113.okserver.org
  gather_facts: True
  sudo: true
  vars_files:
    - "{{ private_dir }}/p.yml"
  roles:
    - role: etherpad-lite
      tags: ['etherpad-lite']
      install_path: /var/www/etherpad-lite
      user: etherpad-lite
      group: etherpad-lite
      version: 1.3.0

- hosts: s120.okserver.org
  sudo: true
  roles:
    - { role: nginx, tags: ['nginx'] }
    - role: python
      tags: ['python']
      install_python3: true

- hosts: s079.okserver.org
  sudo: true
  roles:
    - { role: nginx, tags: ['nginx'] }

- hosts: backup
  gather_facts: True
  sudo: true
  roles:
    - role: rsnapshot
      tags: ['rsnapshot']
      snapshot_root: /home/backup/snapshots/
      cmd_rsync: /usr/bin/rsync
    - role: rsyncd

- hosts: wiki
  gather_facts: false
  sudo: true
  roles:
    - { role: nginx, tags: ['nginx'] }

- hosts: monitoring
  sudo: true
  vars_files:
    - "{{ private_dir }}/p.yml"
  roles:
    - { role: nagios-server, tags: ['nagios-server'] }
    - check-mk-server
    - { role: graphite, tags: ['graphite'] }

- hosts: listserv
  sudo: true
  vars_files:
    - "{{ private_dir }}/p.yml"
  roles:
    # Keep nginx before mailman, as mailman will want to install some config
    # files into /etc/nginx.
    - { role: nginx, tags: ['nginx'] }
    - { role: mailman, tags: ['mailman'] }

- hosts: docker-host
  sudo: true
  vars_files:
    - "{{ private_dir }}/p.yml"
  roles:
    - { role: docker, tags: ['docker'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: postgrey }
    - { role: postfix }

