#ansible-playbook main.yml --tags="base-roles" -vvv
---
- hosts: all
  sudo: true
  vars_files:
    - vars/users.yml
    - "{{ private_dir }}/p.yml"
  roles:
    - { role: check-mk-agent, tags: ['check-mk-agent'] }
    - { role: collectd, tags: ['collectd'] }
    - { role: cron, tags: ['cron'] }
    - { role: iptables-persistent, tags: ['iptables-persistent'] }
    - { role: motd, tags: ['motd'] }
    - { role: nagios-client, tags: ['nagios-client'] }
    - postfix
    - { role: knopki.timezone, tags: ['time'] }
    - { role: bennojoy.ntp, tags: ['time'] }
    - { role: update-notifier, tags: ['update-notifier'] }
    - { role: users, tags: ['users'] }
    - { role: sudo , tags: ['sudo'] }
    - { role: db-backup, tags: ['db-backup'] }
    - { role: apt-mirror-config, tags: ['apt-mirror-config'] }
    - { role: unattended-upgrades, tags: ['unattended-upgrades'] }
    - { role: apt, tags: ['git'], pkg_list: ['git'] }
    - { role: apt, tags: ['sysstat'], pkg_list: ['sysstat'] }
    - { role: sshd, tags: ['sshd'] }

- hosts: s140.okserver.org
  sudo: true
  vars_files:
    - "{{ private_dir }}/p.yml"
  roles:
    - { role: omeka, tags: ['omeka'] }

- hosts: openspending-solr
  sudo: true
  roles:
    - { role: apt, tags: ['python'], pkg_list: ['python-setuptools', 'python-virtualenv'] }
    - { role: supervisor, tags: ['supervisor'] }

- hosts: openspending-web
  sudo: true
  vars_files:
    - "{{ private_dir }}/p.yml"
  roles:
    - { role: varnish, tags: ['varnish'] }
    - { role: nginx, tags: ['nginx'] }

- hosts: s134.okserver.org
  sudo: true
  vars_files:
    - "{{ private_dir }}/p.yml"
  roles:
    - { role: okfn-org-manager, tags: ['heroku-backup'] }

- hosts: s138.okserver.org
  sudo: true
  vars_files:
    - "{{ private_dir }}/p.yml"
  roles:
    - role: awscli
      tags: ['awscli']
      key: "{{ aws_keys[0].key }}"
      secret_key: "{{ aws_keys[0].secret_key }}"
      region: "{{ aws_keys[0].region }}"
      awscli_user: root
      awscli_group: root
      awscli_user_home: /root

- hosts: s079.okserver.org
  sudo: true
  roles:
    - { role: nginx, tags: ['nginx'] }

- hosts: backup
  gather_facts: True
  sudo: true
  roles:
    - role: rsnapshot
      tags: ['rsnapshot']
      snapshot_root: /home/backup/snapshots/
      cmd_rsync: /usr/bin/rsync
    - role: rsyncd

- hosts: wiki
  gather_facts: false
  sudo: true
  roles:
    - { role: nginx, tags: ['nginx'] }
    - { role: php-fpm, tags: ['php-fpm'] }

- hosts: monitoring
  sudo: true
  vars_files:
    - "{{ private_dir }}/p.yml"
  roles:
    - { role: nagios-server, tags: ['nagios-server'] }
    - check-mk-server
    - { role: graphite, tags: ['graphite'] }

- hosts: listserv
  sudo: true
  vars_files:
    - "{{ private_dir }}/p.yml"
  roles:
    # Keep nginx before mailman, as mailman will want to install some config
    # files into /etc/nginx.
    - { role: nginx, tags: ['nginx'] }
    - { role: mailman, tags: ['mailman'] }

- hosts: docker-host
  sudo: true
  vars_files:
    - "{{ private_dir }}/p.yml"
  roles:
    - { role: docker, tags: ['docker'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: postgrey }
    - { role: postfix }

